### ISSUE TITLE
piece type classes are defined in two places

### ISSUE THREAD

**Issue by kyidkim** [team-rook/chess-app#21]
Piece type classes are currently created in the piece.rb file and the individual piece type model files (redundancy).

**Comment by hathcode** [comment]
I was wondering about that, I saw conflicting sources showing different ways of doing this.   I can remove the redundancy from the piece.rb file on my branch and push it with the rest of my changes.  Thanks!

**Comment by hathcode** [comment]
corrected it in the branch I am about to  merge.  Thanks for the eagle eye!

**Comment by kyidkim** [comment]
:+1:
